numpy

In [48]:
#np.array
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [49]:
#2D and 3D
b=np.array([[1,2,3],[2,3,4,]])
print(b)
print(type(b))


[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>


In [50]:
#3D array also called tensor(heigher dimensional array is called tensor)
c=np.array([[1,2,3],[2,3,4,],[4,5,6]])
print(c)
print(type(c))

[[1 2 3]
 [2 3 4]
 [4 5 6]]
<class 'numpy.ndarray'>


In [51]:
#dtype
d=np.array([1,2,3],dtype=float)
e=np.array([1,2,3],dtype=bool)
f=np.array([1,2,3],dtype=complex)
print(d)
print(e)
print(f)

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [52]:
#np.arange :- work like list
a1=np.arange(1,10)
a2=np.arange(1,10,2)
a3=np.arange(1,10,3)
a4=np.arange(1,10,-1)
print(a1,'\n',a2,'\n',a3,'\n',a4)


[1 2 3 4 5 6 7 8 9] 
 [1 3 5 7 9] 
 [1 4 7] 
 []


In [53]:
#with reshape change the
np.arange(1,11).reshape(2,5)
#valid matrix shape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
#np.ones and np.zeros  for value initialization
np.ones((3,4))#np.ones 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
np.zeros((3,4))#np.zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
#np.random :-random value initialization
np.random.random((3,4))

array([[0.24443388, 0.84003611, 0.9818656 , 0.96199216],
       [0.62470641, 0.69572307, 0.24019268, 0.97083767],
       [0.39789393, 0.3096166 , 0.53650598, 0.37922478]])

In [ ]:
#np.linspace linear space
#divide equal distance between two number 
# genrate infinite number between two number . all have equal distance
# np.linespace(x,y,z)
# x:-start y:-end z :- how many no to be genrate 
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [58]:
#np.identity create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [59]:
b1=np.arange(10)
b2=np.arange(12,dtype=float).reshape(3,4)
b3=np.arange(8).reshape(2,2,2)

In [60]:
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
b2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [62]:
b3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
#ndim number of diemension
b1.ndim

1

In [64]:
b2.ndim

2

In [65]:
b3.ndim

3

In [66]:
#shape shape of array
b1.shape

(10,)

In [67]:
b2.shape

(3, 4)

In [68]:
b3.shape

(2, 2, 2)

In [69]:
#size size of array
b1.size

10

In [70]:
b2.size

12

In [71]:
b3.size

8

In [72]:
#itemsize
b3.itemsize

8

In [73]:
#dtype type of data
print(a1.dtype)
print(a1.dtype)
print(a1.dtype)

int64
int64
int64


In [74]:
from numpy import int32
c1=np.arange(10,dtype=int32)
print(c1.dtype)
print(c1.itemsize)


int32
4


changing datatype

In [75]:
#astype reduce data type size
b3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

array operations

In [76]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print("\n")
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [77]:
#scalar operation
#arithmetic
print(a1*2,'\n')
print(a1**2,'\n')
print(a1/2,'\n')
print(a1//2,'\n')
print(a1%2,'\n')

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]] 

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]] 

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]] 

[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]] 

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]] 



In [78]:
#relational
print(a2>5,'\n')
print(a2>15)


[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [79]:
#vector operation
print(a1*a2,'\n')
print(a1*a2,'\n')
print(a1/a2,'\n')
print(a1//a2,'\n')

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]] 

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]] 

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 



In [80]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[60., 11., 53.],
       [ 6., 37., 79.],
       [47., 45., 62.]])

In [81]:
#max/min/sum/prod
print(np.max(a1))#max value in given array
print(np.min(a1))#minvalue in given array
print(np.sum(a1))#sum of all element of array
print(np.prod(a1))#product of all element in array

#0:- col and 1->row
print(np.max(a1,axis=1))#max value of each row
print(np.max(a1,axis=0))#max value of each column
print(np.min(a1,axis=0))
print(np.sum(a1,axis=1))#row by sum of element

79.0
6.0
400.0
80445532741200.0
[60. 79. 62.]
[60. 45. 79.]
[ 6. 11. 53.]
[124. 122. 154.]


In [82]:
#mean/median/std/var
#same rule
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))
print(np.mean(a1,axis=0))

44.44444444444444
47.0
22.30152516513967
497.35802469135797
[37.66666667 31.         64.66666667]


In [83]:
#trigometric function
np.sin(a1)

array([[-0.30481062, -0.99999021,  0.39592515],
       [-0.2794155 , -0.64353813, -0.44411267],
       [ 0.12357312,  0.85090352, -0.7391807 ]])

In [84]:
#dot product or vector product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)#result=(3,3) matrix

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [85]:
#log and exponent
print(np.log(a1))
print("\n")
print(np.exp(a1))

[[4.09434456 2.39789527 3.97029191]
 [1.79175947 3.61091791 4.36944785]
 [3.8501476  3.80666249 4.12713439]]


[[1.14200739e+26 5.98741417e+04 1.04137594e+23]
 [4.03428793e+02 1.17191424e+16 2.03828107e+34]
 [2.58131289e+20 3.49342711e+19 8.43835667e+26]]


In [86]:
#round/floor/cell
np.random.random((2,3))

array([[0.1594378 , 0.11992781, 0.35563142],
       [0.51203196, 0.24759579, 0.22469631]])

In [87]:
#for integer
np.round(np.random.random((2,3)))
#round down to the nearest value   3.9->4,3.1->3

array([[0., 1., 0.],
       [0., 0., 1.]])

In [88]:
#for integer
np.floor(np.random.random((2,3)))
#round down to the nearest integer 3.9->3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
#for integer
np.ceil(np.random.random((2,3)))
# round up to the nearest  integer 3.9->4

array([[1., 1., 1.],
       [1., 1., 1.]])

indexing and slicing

indexing single element fetch

In [90]:
b1=np.arange(10)
b2=np.arange(12,dtype=float).reshape(3,4)
b3=np.arange(8).reshape(2,2,2)

In [91]:
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
b1[-1]# last element negative indexing

np.int64(9)

In [93]:
b1[0]#zero index positive indexing

np.int64(0)

In [94]:
b2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [95]:
b2[1,2]#both row and colummn 

np.float64(6.0)

In [96]:
b3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [97]:
b3[1,0,1]#5

np.int64(5)

In [98]:
# fetch 0
b3[0,0,0]

np.int64(0)

In [99]:
#fetch 6
b3[1,1,0]

np.int64(6)

slicing multiple element fetch

In [100]:
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
b1[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
b1[2:7:2]#skip  2 index same as list

array([2, 4, 6])

In [103]:
b2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [104]:
b2[0,:]

array([0., 1., 2., 3.])

In [105]:
b2[:,2]

array([ 2.,  6., 10.])

In [ ]:
b2[1:,1:3]#3 not included

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
b2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
#fetch 1,3,9,11
b2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [110]:
# fetch 4,7
b2[1,::3]

array([4., 7.])

In [111]:
# fetch 1,2,3,5,6,7
b2[:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [114]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [125]:
#fetch 0,2,18,20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [123]:
#fetch 22 ,23,25 ,26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [121]:
#fetch 2nd column of second 2d array
a3[1,:,1]

array([10, 13, 16])

In [119]:
#fetch 2nd row of first 2d array
a3[0,1]

array([3, 4, 5])

In [118]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [117]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

iterating

In [126]:
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
for i in b1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [127]:
b2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [132]:
for i in b2:
    print(i)# every time print a row

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [137]:
for i in np.nditer(b2):
    print(i)# iteration for every element 

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [128]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [134]:
for i in a3:
    print(i)# every time print 2d array for 3d loop

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
    print(i) # iterating for every element

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


reshape

In [ ]:
#reshape

In [140]:
# transpose
np.transpose(b2)

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [141]:
b2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [144]:
#ravel convert into one day array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

stacking

In [151]:
#horizontal 
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [147]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5,a4))#add many but shape are same

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [154]:
#vartical
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)


In [157]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [155]:
np.vstack((a4,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

spliting

In [ ]:
#horizontal spliting
np.hsplit(a4,2)
# column by spliting in equal part

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
np.hsplit(a4,4)
# column by spliting in equal part

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
#vertical spliting
np.vsplit(a4,3)# row by spliting in equal part

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [ ]:
np.vsplit(a5,3) # row by spliting in equal part

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]