### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [3]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[35, 53,  4,  4],
       [18, 13, 30, 40],
       [ 6, 63, 62, 55],
       [ 2, 11,  2, 72],
       [72, 37,  7, 20],
       [73,  3, 65, 98]], dtype=int32)

In [4]:
np.sort(a)

array([ 5,  6,  7, 14, 19, 20, 30, 33, 39, 43, 54, 67, 79, 80, 89],
      dtype=int32)

In [ ]:
np.sort(b)#row by sorting

array([[ 4,  4, 35, 53],
       [13, 18, 30, 40],
       [ 6, 55, 62, 63],
       [ 2,  2, 11, 72],
       [ 7, 20, 37, 72],
       [ 3, 65, 73, 98]], dtype=int32)

In [ ]:
np.sort(b,axis=1)#row by axis=1 

array([[ 4,  4, 35, 53],
       [13, 18, 30, 40],
       [ 6, 55, 62, 63],
       [ 2,  2, 11, 72],
       [ 7, 20, 37, 72],
       [ 3, 65, 73, 98]], dtype=int32)

In [7]:
np.sort(b,axis=0)#column  by axis=0

array([[ 2,  3,  2,  4],
       [ 6, 11,  4, 20],
       [18, 13,  7, 40],
       [35, 37, 30, 55],
       [72, 53, 62, 72],
       [73, 63, 65, 98]], dtype=int32)

In [8]:
#decending order
np.sort(a)[::-1]

array([89, 80, 79, 67, 54, 43, 39, 33, 30, 20, 19, 14,  7,  6,  5],
      dtype=int32)

In [13]:
#decending order
np.sort(b,axis=1)[:,::-1]

array([[53, 35,  4,  4],
       [40, 30, 18, 13],
       [63, 62, 55,  6],
       [72, 11,  2,  2],
       [72, 37, 20,  7],
       [98, 73, 65,  3]], dtype=int32)

In [11]:
#decending order
np.sort(b,axis=0)[::-1]

array([[73, 63, 65, 98],
       [72, 53, 62, 72],
       [35, 37, 30, 55],
       [18, 13,  7, 40],
       [ 6, 11,  4, 20],
       [ 2,  3,  2,  4]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [14]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [15]:
np.append(a,200)

array([ 89,   7,   6,  39,  14,  19,  80,  79,  67,  43,  30,  54,  20,
         5,  33, 200])

In [16]:
b

array([[35, 53,  4,  4],
       [18, 13, 30, 40],
       [ 6, 63, 62, 55],
       [ 2, 11,  2, 72],
       [72, 37,  7, 20],
       [73,  3, 65, 98]], dtype=int32)

In [17]:
np.append(b,np.ones((b.shape[0],1)))

array([35., 53.,  4.,  4., 18., 13., 30., 40.,  6., 63., 62., 55.,  2.,
       11.,  2., 72., 72., 37.,  7., 20., 73.,  3., 65., 98.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [18]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[35., 53.,  4.,  4.,  1.],
       [18., 13., 30., 40.,  1.],
       [ 6., 63., 62., 55.,  1.],
       [ 2., 11.,  2., 72.,  1.],
       [72., 37.,  7., 20.,  1.],
       [73.,  3., 65., 98.,  1.]])

In [22]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[3.50000000e+01, 5.30000000e+01, 4.00000000e+00, 4.00000000e+00,
        8.05058017e-01],
       [1.80000000e+01, 1.30000000e+01, 3.00000000e+01, 4.00000000e+01,
        7.26301451e-01],
       [6.00000000e+00, 6.30000000e+01, 6.20000000e+01, 5.50000000e+01,
        6.78684544e-03],
       [2.00000000e+00, 1.10000000e+01, 2.00000000e+00, 7.20000000e+01,
        7.65494708e-01],
       [7.20000000e+01, 3.70000000e+01, 7.00000000e+00, 2.00000000e+01,
        2.25536295e-02],
       [7.30000000e+01, 3.00000000e+00, 6.50000000e+01, 9.80000000e+01,
        8.96636342e-01]])

In [21]:
np.append(b,np.random.randint(1,100,(b.shape[0],1)),axis=1)

array([[35, 53,  4,  4, 55],
       [18, 13, 30, 40, 13],
       [ 6, 63, 62, 55, 37],
       [ 2, 11,  2, 72, 39],
       [72, 37,  7, 20, 27],
       [73,  3, 65, 98, 87]], dtype=int32)

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [23]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [25]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [28]:
e=np.array([1,2,3,4,5,6,7,8,9,7,4,5,6,7,7,8,9,4,32,2,2,5,7,8,89,5,23,2,9])
print(e)


[ 1  2  3  4  5  6  7  8  9  7  4  5  6  7  7  8  9  4 32  2  2  5  7  8
 89  5 23  2  9]


In [29]:
np.unique(e)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 23, 32, 89])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [30]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [32]:
np.expand_dims(a,axis=0)

array([[89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33]],
      dtype=int32)

In [31]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [33]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [34]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [35]:
#find all indices with value greater than 50
np.where(a>50)

(array([ 0,  6,  7,  8, 11]),)

In [36]:
#replace all values >50 with 0
np.where(a>50,0,a)

array([ 0,  7,  6, 39, 14, 19,  0,  0,  0, 43, 30,  0, 20,  5, 33],
      dtype=int32)

In [37]:
#replace all  even with zero
np.where(a%2==0,0,a)

array([89,  7,  0, 39,  0, 19,  0, 79, 67, 43,  0,  0,  0,  5, 33],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [38]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [40]:
np.argmax(a)

np.int64(0)

In [39]:
b

array([[35, 53,  4,  4],
       [18, 13, 30, 40],
       [ 6, 63, 62, 55],
       [ 2, 11,  2, 72],
       [72, 37,  7, 20],
       [73,  3, 65, 98]], dtype=int32)

In [41]:
np.argmax(b,axis=0)

array([5, 2, 5, 5])

In [42]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 0, 3])

argmin

In [44]:
np.argmin(a)

np.int64(13)

In [45]:
np.argmin(b,axis=0)

array([3, 5, 3, 0])

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [46]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [48]:
np.cumsum(a)

array([ 89,  96, 102, 141, 155, 174, 254, 333, 400, 443, 473, 527, 547,
       552, 585])

In [49]:
b

array([[35, 53,  4,  4],
       [18, 13, 30, 40],
       [ 6, 63, 62, 55],
       [ 2, 11,  2, 72],
       [72, 37,  7, 20],
       [73,  3, 65, 98]], dtype=int32)

In [50]:
np.cumsum(b)

array([ 35,  88,  92,  96, 114, 127, 157, 197, 203, 266, 328, 383, 385,
       396, 398, 470, 542, 579, 586, 606, 679, 682, 747, 845])

In [51]:
np.cumsum(b,axis=0)

array([[ 35,  53,   4,   4],
       [ 53,  66,  34,  44],
       [ 59, 129,  96,  99],
       [ 61, 140,  98, 171],
       [133, 177, 105, 191],
       [206, 180, 170, 289]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 35,  53,   4,   4],
       [ 53,  66,  34,  44],
       [ 59, 129,  96,  99],
       [ 61, 140,  98, 171],
       [133, 177, 105, 191],
       [206, 180, 170, 289]])

cumprod

In [53]:
np.cumprod(a)

array([                  89,                  623,                 3738,
                     145782,              2040948,             38778012,
                 3102240960,         245077035840,       16420161401280,
            706066940255040,    21182008207651200,  1143828443213164800,
        4429824790553744384,  3702379879059170304, -6948672507014241280])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [54]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [55]:
np.percentile(a,100)

np.float64(89.0)

In [56]:
np.percentile(a,0)

np.float64(5.0)

In [57]:
np.percentile(a,50)

np.float64(33.0)

In [60]:
np.percentile(a,75)

np.float64(60.5)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [61]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [62]:
np.histogram(a)

(array([3, 3, 1, 1, 2, 1, 0, 1, 2, 1]),
 array([ 5. , 13.4, 21.8, 30.2, 38.6, 47. , 55.4, 63.8, 72.2, 80.6, 89. ]))

In [65]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 2, 1, 3, 1, 1, 1, 1, 2, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [66]:
np.histogram(a,bins=[0,50,100])

(array([10,  5]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [69]:
salary=np.array([20000,30000,40000,50000,60000,70000,80000])
experience=np.array([2,2,3,4,3,4,4])

np.corrcoef(salary,experience)

array([[1.        , 0.85749293],
       [0.85749293, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [70]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [71]:
items=[10,20,30,40,60,70,80]
np.isin(a,items)

array([False, False, False, False, False, False,  True, False, False,
       False,  True, False,  True, False, False])

In [73]:
a[np.isin(a,items)]

array([80, 30, 20], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [74]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [76]:
np.flip(a)#mirror image

array([33,  5, 20, 54, 30, 43, 67, 79, 80, 19, 14, 39,  6,  7, 89],
      dtype=int32)

In [77]:
b

array([[35, 53,  4,  4],
       [18, 13, 30, 40],
       [ 6, 63, 62, 55],
       [ 2, 11,  2, 72],
       [72, 37,  7, 20],
       [73,  3, 65, 98]], dtype=int32)

In [78]:
np.flip(b)

array([[98, 65,  3, 73],
       [20,  7, 37, 72],
       [72,  2, 11,  2],
       [55, 62, 63,  6],
       [40, 30, 13, 18],
       [ 4,  4, 53, 35]], dtype=int32)

In [79]:
np.flip(b,axis=0)

array([[73,  3, 65, 98],
       [72, 37,  7, 20],
       [ 2, 11,  2, 72],
       [ 6, 63, 62, 55],
       [18, 13, 30, 40],
       [35, 53,  4,  4]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [80]:
a

array([89,  7,  6, 39, 14, 19, 80, 79, 67, 43, 30, 54, 20,  5, 33],
      dtype=int32)

In [ ]:
np.put(a,[0,1],[110,530])
#permenent change on array
a

array([110, 530,   6,  39,  14,  19,  80,  79,  67,  43,  30,  54,  20,
         5,  33], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [83]:
a

array([110, 530,   6,  39,  14,  19,  80,  79,  67,  43,  30,  54,  20,
         5,  33], dtype=int32)

In [ ]:
np.delete(a,0)#0 index

array([530,   6,  39,  14,  19,  80,  79,  67,  43,  30,  54,  20,   5,
        33], dtype=int32)

In [86]:
np.delete(a,[0,2,3])

array([530,  14,  19,  80,  79,  67,  43,  30,  54,  20,   5,  33],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.isin

In [91]:
n=np.array([1,2,3,4,5])
m=np.array([6,7,8,9,3,4])

In [92]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.intersect1d(n,m)

array([3, 4])

In [94]:
np.setdiff1d(m,n)

array([6, 7, 8, 9])

In [95]:
np.setxor1d(n,m)

array([1, 2, 5, 6, 7, 8, 9])

In [99]:
np.isin(m,n)

array([False, False, False, False,  True,  True])

In [101]:
m[np.isin(m,n)]

array([3, 4])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [102]:
a

array([110, 530,   6,  39,  14,  19,  80,  79,  67,  43,  30,  54,  20,
         5,  33], dtype=int32)

In [103]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 39, 25, 25, 75, 75, 67, 43, 30, 54, 25, 25, 33],
      dtype=int32)