NumPy

NumPy (Numerical Python) is an open-source Python library used for numerical computing. Its main object is the ndarray, a multidimensional array designed for efficient operations on numerical data.

NumPy performs the operation element by element.

This type of operation is called vectorization.

In [1]:
import numpy as np

In [2]:
numbers = np.array([10, 20, 30, 40])
numbers * 2

array([20, 40, 60, 80])

NumPy Array — ndarray

An ndarray is NumPy's fundamental data structure. It represents a multidimensional, generally homogeneous collection of elements.

In [3]:
a = np.array([10, 20, 30, 40])
print(a)
print(type(a))

[10 20 30 40]
<class 'numpy.ndarray'>


Creating an Array — np.array()

np.array() creates a NumPy ndarray from an array-like object such as a list or tuple.

In [4]:
np.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

array(<class 'object'>, dtype=object)

In [5]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [6]:
a = np.array((10, 20, 30))
print(a)

[10 20 30]


Dimensions of an Array

A NumPy array can have different dimensions.

In [ ]:
#1D array
a = np.array([1, 2, 3, 4])

In [7]:
#2D array
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a = np.array([
    [[1, 2],[3, 4]],
    [[5, 6],[7, 8]]
])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

ndim

ndim returns the number of dimensions (axes) of an array.

In [10]:
#ndim
array = np.array([1, 2, 3, 4])
array.ndim

1

In [11]:
array = np.array([[1, 2, 3, 4]])
array.ndim

2

shape

shape returns the size of the array along each dimension.

In [12]:
#shape
array.shape

(1, 4)

In [13]:
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a.shape)

(2, 3)


astype

astype() change the value of data type

In [48]:
arr = np.array([1.2, 2.5, 3.7], dtype=np.float64)
print(arr.dtype)
print(arr.itemsize)
arr = arr.astype(np.float32)
print(arr.dtype)
print(arr.itemsize)
arr = arr.astype(np.float16)
print(arr.dtype)
print(arr.itemsize)

float64
8
float32
4
float16
2


size

size returns the total number of elements in an array.


In [14]:
#size
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a.size)

6


dtype

dtype tells you the data type of the elements in an array.

In [15]:
#dtype
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [ ]:
a = np.array([1, 2, 3], dtype=float)
print(a)

[1. 2. 3.]


itemsize

itemsize returns the number of bytes used by one element.

In [17]:
#itemsize
a = np.array([1, 2, 3])
print(a.itemsize)

8


nbytes

nbytes returns the total number of bytes consumed by the array elements.

In [18]:
#nbytes
a = np.array([1, 2, 3])
print(a.nbytes)

24


Creating an Array of Zeros — np.zeros()

np.zeros() creates an array where every element is 0.

np.zeros(shape, dtype=float)

In [19]:
np.zeros(5, dtype=float)

array([0., 0., 0., 0., 0.])

In [20]:
a = np.zeros((2, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


np.ones()

Creates an array filled with 1.

np.ones(shape, dtype=None)

In [21]:
np.ones(5, dtype=None)

array([1., 1., 1., 1., 1.])

In [22]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


np.full()

Creates an array of a specified shape filled with a specified value.

np.full(shape, fill_value, dtype=None)

In [23]:
a = np.full((2, 3), 7)
print(a)

[[7 7 7]
 [7 7 7]]


np.empty()

Creates an array without initializing its elements to a particular value.

np.empty(shape, dtype=float)

In [24]:
a = np.empty(5)
print(a)

[1. 1. 1. 1. 1.]


np.arange()

np.arange() creates values within a range using a specified step.

np.arange(start, stop, step)

In [25]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [26]:
a = np.arange(0, 20, 2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


np.linspace()

np.linspace() generates a specified number of evenly spaced values between two endpoints.

np.linspace(start, stop, num=50)

In [27]:
a = np.linspace(0, 10, 5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


np.eye()

Creates a 2D array with ones on the main diagonal and zeros elsewhere.



In [28]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.identity()

Creates a square identity matrix.

In [29]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.diag()

np.diag() can:

Create a diagonal matrix from a 1D array.

Extract a diagonal from a 2D array.

In [30]:
a = np.diag([1, 2, 3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [31]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(np.diag(a))

[1 5 9]


Indexing

Indexing means accessing a specific element of an array.



In [32]:
a = np.array([10, 20, 30, 40])
print(a[0])

10


In [33]:
#Negative Indexing
a = np.array([10, 20, 30, 40])
print(a[-1])

40


Slicing

Slicing means extracting a portion of an array.

array[start:stop:step]

In [34]:
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])

[20 30 40]


2D Indexing

array[row, column]

In [35]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(a[0, 1])

20


In [36]:
#Selecting a Row
print(a[0])

[10 20 30]


In [37]:
#Selecting a Column
print(a[:, 1])

[20 50]


Boolean Indexing

Boolean indexing selects elements based on a condition.

In [38]:
a = np.array([10, 20, 30, 40, 50])
print(a[a > 25])

[30 40 50]


Arithmetic Operations

NumPy supports vectorized arithmetic.

In [43]:
a = np.array([10, 20, 30])
print(a + 5)
print(a - 5)
print(a * 5)
print(a / 5)
print(a ** 2)

[15 25 35]
[ 5 15 25]
[ 50 100 150]
[2. 4. 6.]
[100 400 900]


Element-wise Operations

In [46]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a+b)
print(a-b)

[11 22 33]
[ 9 18 27]


Universal Functions — ufuncs

A ufunc (universal function) is a NumPy function that performs an operation element-by-element on arrays.

In [50]:
a = np.array([4, 9, 16])
print(np.sqrt(a))
print(np.abs(a))
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.floor(a))
print(np.ceil(a))

[2. 3. 4.]
[ 4  9 16]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]
[-0.7568025   0.41211849 -0.28790332]
[-0.65364362 -0.91113026 -0.95765948]
[ 4  9 16]
[ 4  9 16]


np.abs()

Returns the absolute value of each element.

In [51]:
a = np.array([-10, -5, 2])
print(np.abs(a))

[10  5  2]


np.square()

Returns the square of each element.

In [52]:
a = np.array([2, 3, 4])
print(np.square(a))

[ 4  9 16]


In [53]:
#np.round()
np.round(3.14159, 2)

np.float64(3.14)

In [55]:
# np.ceil() : Rounds up
np.ceil(3.1)

np.float64(4.0)

Trigonometric Functions

np.sin()

np.cos()

np.tan()


np.arcsin()

np.arccos()

np.arctan()

In [56]:
np.sin(np.pi / 2)

np.float64(1.0)

Aggregation Functions

Aggregation functions reduce multiple values into a summary value.

Important functions:

np.sum()
np.mean()
np.median()
np.min()
np.max()
np.std()
np.var()

In [58]:
#np.sum()
a = np.array([10, 20, 30, 40])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))


100
25.0
25.0
10
40
11.180339887498949
125.0


argmax()

Returns the index of the maximum value.

np.argmin()

Returns the index of the minimum value.

In [59]:
a = np.array([10, 50, 20, 30])
print(np.argmax(a))

1


Axis

This is one of the most important NumPy concepts.

In [60]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
np.sum(a, axis=0)

array([50, 70, 90])

In [61]:
np.sum(a, axis=1)

array([ 60, 150])

reshape()

Changes the shape of an array without changing its data.

In [62]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

[[1 2 3]
 [4 5 6]]


flatten()

Converts a multidimensional array into a 1D array and returns a copy.

In [63]:
a = np.array([
    [1, 2],
    [3, 4]
])
print(a.flatten())

[1 2 3 4]


ravel()

Converts an array into one dimension and returns a view when possible.

In [64]:
print(a.ravel())

[1 2 3 4]


Transpose

Transpose changes the axes of an array. For a 2D matrix, rows become columns and columns become rows.

In [65]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [66]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

np.concatenate()

Joins arrays along an existing axis.

In [67]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b)))

[1 2 3 4 5 6]


np.stack()

Joins arrays along a new axis.

In [68]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.stack((a, b)))

[[1 2 3]
 [4 5 6]]


np.vstack()

Vertically stacks arrays.

In [69]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

np.hstack()

Horizontally stacks arrays.

In [70]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

Splitting Arrays

np.split()

Splits an array into multiple sub-arrays.

In [71]:
a = np.array([1, 2, 3, 4, 5, 6])
result = np.split(a, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


np.where()

np.where() selects positions or values based on a condition.

It returns the indexes where the condition is true.

In [72]:
a = np.array([10, 20, 30, 40])
print(np.where(a > 20))

(array([2, 3]),)


It can also choose between two values:

In [73]:
result = np.where(a >= 30, "Pass", "Fail")
print(result)

['Fail' 'Fail' 'Pass' 'Pass']


np.unique()

Returns the unique elements of an array.

In [74]:
a = np.array([10, 20, 20, 30, 30, 30])
print(np.unique(a))

[10 20 30]


In [75]:
values, counts = np.unique(a, return_counts=True)
print(values)
print(counts)

[10 20 30]
[1 2 3]


np.sort()

Returns a sorted copy of an array.

In [76]:
a = np.array([40, 10, 30, 20])
print(np.sort(a))

[10 20 30 40]


np.argsort()

Returns the indices that would sort the array.

In [77]:
a = np.array([40, 10, 30, 20])
print(np.argsort(a))

[1 3 2 0]


np.any()

Returns True if at least one element is True.

In [78]:
a = np.array([False, False, True])
print(np.any(a))

True


np.all()

Returns True only if all elements are True.

In [79]:
a = np.array([True, True, True])
print(np.all(a))

True


Logical Functions

np.logical_and()

np.logical_or()

np.logical_not()

np.logical_xor()

In [80]:
a = np.array([10, 20, 30, 40])
result = np.logical_and(a > 15, a < 35)
print(result)

[False  True  True False]


np.clip()

Limits values to a specified minimum and maximum range.

In [81]:
a = np.array([10, 30, 50, 70])
print(np.clip(a, 20, 60))

[20 30 50 60]


NaN

NaN means Not a Number and is commonly used to represent missing numerical values.

In [82]:
a = np.array([10, np.nan, 30])
print(np.mean(a))

nan


In [ ]:
#nanmean()
print(np.nanmean(a))

20.0


np.isnan()

np.isfinite()

np.isinf()


np.nanmean()

np.nanmedian()

np.nanmin()

np.nanmax()

np.nansum()

np.nanstd()

np.nanvar()

Data Type Conversion — astype()

astype() creates an array converted to a specified data type.

In [86]:
a = np.array([1, 2, 3])
b = a.astype(np.float32)
print(b)
print(b.dtype)

[1. 2. 3.]
float32


Copy

A copy creates a separate array with independent data.

In [87]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


View

A view is another way of accessing the same underlying data.

In [88]:
a = np.array([1, 2, 3])
b = a.view()
b[0] = 100
print(a)

[100   2   3]


Broadcasting

Broadcasting is NumPy's mechanism for performing operations between arrays with compatible shapes without manually creating matching arrays.

In [89]:
a = np.array([10, 20, 30])
print(a + 5)

[15 25 35]


Random Number Generation


In [91]:
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x2807EE35700

In [93]:
rng.random(5).round(2)

array([0.51, 0.47, 0.06, 0.83, 0.14])

In [ ]:
#Generates five integers from 1 through 9.
rng.integers(1, 10, size=5)

array([2, 3, 1, 9, 8])

Random choice

In [95]:
rng.choice([10, 20, 30, 40])

np.int64(20)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
rng.shuffle(a)
print(a)

[4 1 3 2 5]


Statistics

np.mean()

np.median()

np.std()

np.var()

np.min()

np.max()

np.percentile()

np.quantile()

In [97]:
marks = np.array([40, 50, 60, 70, 80])
print(np.percentile(marks, 50))

60.0


Percentile

the value below which a given percentage of observations falls.

The 50th percentile is the median.

In [98]:
marks = np.array([40, 50, 60, 70, 80])
np.percentile(marks, 50)

np.float64(60.0)

Quantile

A quantile is similar to a percentile but uses a value between 0 and 1.

In [99]:
np.quantile(marks, 0.5)

np.float64(60.0)

Correlation — np.corrcoef()

corrcoef() calculates a correlation coefficient matrix.

A value close to 1 indicates a strong positive linear relationship.

In [101]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
print(np.corrcoef(x, y))

[[1. 1.]
 [1. 1.]]


Histogram — np.histogram()

np.histogram() calculates the frequency distribution of numerical data across bins.

In [102]:
a = np.array([1, 2, 2, 3, 3, 3, 4])
hist, bins = np.histogram(a)
print(hist)
print(bins)

[1 0 0 2 0 0 3 0 0 1]
[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4. ]


Linear Algebra — np.linalg

np.linalg is NumPy's linear algebra module.

np.linalg.det()

np.linalg.inv()

np.linalg.solve()

np.linalg.eig()

np.linalg.norm()

Matrix Multiplication — @

In [103]:
A = np.array([
    [1, 2],
    [3, 4]
])
B = np.array([
    [5, 6],
    [7, 8]
])
C = A @ B
print(C)

[[19 22]
 [43 50]]


np.matmul()

Performs matrix multiplication.

In [104]:
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

np.dot()

Performs dot-product operations. Its behavior depends on the dimensions of the inputs.


In [105]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))

32


Matrix Determinant

The determinant is a scalar value associated with a square matrix.

In [106]:
A = np.array([
    [1, 2],
    [3, 4]
])
print(np.linalg.det(A))

-2.0000000000000004


Matrix Inverse

np.linalg.inv() calculates the inverse of a square, nonsingular matrix.

In [107]:
A = np.array([
    [1, 2],
    [3, 4]
])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


Solving Linear Equations

np.linalg.solve() solves a system of linear equations.

In [108]:
A = np.array([
    [2, 1],
    [1, 3]
])
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print(x)

[1.8 1.4]


Saving NumPy Arrays

np.save()

Saves a single NumPy array in .npy format.

In [110]:
a = np.array([10, 20, 30])
np.save("data.npy", a)

In [111]:
#load it
a = np.load("data.npy")
print(a)

[10 20 30]


np.savez()

Saves multiple NumPy arrays in a single .npz file.

In [112]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.savez("data.npz", first=a, second=b)

In [113]:
data = np.load("data.npz")
print(data["first"])
print(data["second"])

[1 2 3]
[4 5 6]
